### ISSUE TITLE
Plugin with id 'maven' not found

### ISSUE THREAD

**Issue by msaadqureshi** [gusparis/react-native-month-year-picker#117]
**Using Gradle up to 7.x**

1: Task failed with an exception.
-----------
* Where:
Build file 'F:\ProjectName\node_modules\react-native-month-year-picker\android\build.gradle' line: 24   

* What went wrong:
A problem occurred evaluating project ':react-native-month-year-picker'.
> **Plugin with id 'maven' not found.**

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-month-year-picker'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle   

* Where:
Build file 'F:\RNproject\HomeTutorsClub\node_modules\react-native-month-year-picker\android\build.gradle' line: 145  

* What went wrong:
A problem occurred configuring project ':react-native-month-year-picker'.
> Could not find method mavenDeployer() for arguments [build_w8d36fywccdljicuzzkzcig1$_run_closure4$_closure15$_closure

**Comment by bumjoo** [comment]
I have same problem.

**Comment by phuocantd** [comment]
+1

**Comment by vksgautam1** [comment]
same issue

**Comment by vg3900** [comment]
Same Issue.
I can see that the PR for this issue is merged with the master.
@gusparis Please release the new version of the package.

**Comment by AbdullhRtima** [comment]
Is this issue been solved or not I am still facing this error?

**Comment by gusparis** [comment]
Fixed on #140. Can you guys check?
