### ISSUE TITLE
build app fail 

### ISSUE THREAD

**Issue by phamhieu1412** [gusparis/react-native-month-year-picker#136]
today when i build app on android, i have error. what happen?
react-native: 0.63.2
react-native-month-year-picker: 1.8.1

<img width="891" alt="Screen Shot 2022-10-31 at 10 56 41" src="https://user-images.githubusercontent.com/48906710/198928198-fd46f5b3-9f93-444e-9916-4fc51b8b0fbe.png">

**Comment by TOPSinfo** [comment]
+1

**Comment by ydv0121** [comment]
+1

**Comment by TOPSinfo** [comment]
#35136

**Comment by yasithg** [comment]
@phamhieu1412 @ydv0121 any solution yet ?

**Comment by ydv0121** [comment]
Incident resolved

https://status.gradle.com/

**Comment by gusparis** [comment]
Fixed on #140. Can you guys check?
