### ISSUE TITLE
Error when building app - Could not resolve all files for configuration ':react-native-month-year-picker:implementation'

### ISSUE THREAD

**Issue by tacianoscur** [gusparis/react-native-month-year-picker#139]
When running the app on android, I get this error: "Could not resolve all files for configuration ':react-native-month-year-picker:implementation'", here's the screenshot:

My RN version is `0.70.3` and react-native-month-year-picker version is `^1.8.2`.

![image](https://user-images.githubusercontent.com/53914601/201222588-32ab56f8-57a8-4844-8dca-9ded8d0c3298.png)

I was able to fix it when removing this line from `android/build.gradle` but it should work without changing anything from the package:

![image](https://user-images.githubusercontent.com/53914601/201223037-e2a4d032-0e5e-42aa-8069-d745badf5aa7.png)

**Comment by sudharsanvishnu** [comment]
same error

**Comment by ydv0121** [comment]
+1

**Comment by gusparis** [comment]
Hello! Thanks for using the library! I've been working on this one and a couple of other issues reported. I'm hoping to have a new version by EOW. Regards!

**Comment by jimsideout** [comment]
@gusparis and update on this?

**Comment by sazzadh88** [comment]
@gusparis I have same issue

`* Where:
Build file 'C:\Users\sazza\Projects\ReactNative\taxi\node_modules\react-native-month-year-picker\android\build.gradle' line: 115

* What went wrong:
A problem occurred configuring project ':react-native-month-year-picker'.
> Could not resolve all files for configuration ':react-native-month-year-picker:implementation'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-month-year-picker     
      > Cannot choose between the following variants of com.facebook.react:react-native:0.70.5:
          - debugVariantDefaultRuntimePublication    
          - releaseVariantDefaultRuntimePublication  
        All of them match the consumer attributes:   
          - Variant 'debugVariantDefaultRuntimePublication' capability com.facebook.react:react-native:0.70.5:`

**Comment by gusparis** [comment]
Fixed on #140. Can you guys check?
