### ISSUE TITLE
Any plans to make this package compatible with Expo/Expo Go?

### ISSUE THREAD

**Issue by Roka20012** [gusparis/react-native-month-year-picker#146]
Hey!
Thanks for a great package, I am curious Are there any plans to make this package compatible with Expo?
Since Expo is a great tool nowadays, it would be nice to see this package compatible with the expo.

https://docs.expo.dev/modules/overview/

Currently doesn't work with Expo

Tested: 
expo:   "^48.0.9"

![image](https://user-images.githubusercontent.com/32239452/231395942-86725654-cf4e-465f-ab96-106dadaee281.png)

**Comment by Episodex** [comment]
It works when you use [Expo dev client](https://docs.expo.dev/develop/development-builds/introduction/).
