### ISSUE TITLE
TypeError: undefined is not an object (evaluating _reactNative.Appearance.getColorScheme)

### ISSUE THREAD

**Issue by DaniyarJakupov** [gusparis/react-native-month-year-picker#17]
Thanks for the lib!

On iOS it throws an error: 
`TypeError: undefined is not an object (evaluating _reactNative.Appearance.getColorScheme)`
Android works fine. 

![Screenshot 2020-06-15 at 16 43 52](https://user-images.githubusercontent.com/17025967/84671414-a54b9200-af27-11ea-9897-b236b8669565.png)

Versions:
 "react": "16.9.0",
 "react-native": "0.61.5",

**Comment by gusparis** [comment]
You're welcome! Unfortunately, `Appearance` was in RN 0.62.2 (https://reactnative.dev/docs/appearance). Either way, I should make a workaround for lower RN versions. Will try to make a new release today, end of my day.

**Comment by DaniyarJakupov** [comment]
> You're welcome! Unfortunately, `Appearance` was introduced in RN 0.62.2 (https://reactnative.dev/docs/appearance). Either way, I should make a workaround for lower RN versions. Will try to make a new release today, end of my day.

Thanks! Any update? :)

**Comment by gusparis** [comment]
Hey! Sorry! Making a release to the stores right now and it's been crazy. I have the iOS fix, with some new features too, working on the Android changes to accept Dark Theme config as well (Android 10+). Will be doing a push tonight.
