### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNMonthPicker" was not found in the UIManager.  

### ISSUE THREAD

**Issue by Atuldhaka** [gusparis/react-native-month-year-picker#23]
This occurs when we try to use this library for typescript project, help needed.

**Comment by gusparis** [comment]
Hey! I think this has nothing to do with you having typescript. Looks more like a linking issue. RN version? If you are on RN < 0.60 you will hace to perform the linking manually.

**Comment by Atuldhaka** [comment]
Hi, actually i am using this in typescript and it is then asking for the types and when i try to install types with this  --------------->'@types/react-native-month-year-picker@latest' it says it is not in the npm registry. And i am using this library in  react native version : - 0.62.2 and i have followed these steps to install : - 
1. npm install react-native-month-year-picker --save
2. npx pod-install
3. then i restarted metro bundler and tries running. 
and then when i import this and then run then it gives the above error.
