### ISSUE TITLE
Expo

### ISSUE THREAD

**Issue by onebrunoo** [gusparis/react-native-month-year-picker#26]
Cannot read property 'open' of undefined for MonthPicker.

**Comment by gusparis** [comment]
@onebrunoo you can't use this library with Expo. It states this very clearly in [the docs](https://docs.expo.io/introduction/faq/?redirected):

> But no native modules…
   The most limiting thing about Expo is that you can’t add in your own native modules without detaching and using ExpoKit. Continue reading the next question for a full explanation.

If you want to use anything that requires `react-native link`, then you need to detach your project.

Sorry! 
Let me know if you need anything else.
