### ISSUE TITLE
App crashes while opening react native month year picker

### ISSUE THREAD

**Issue by choudhary1200** [gusparis/react-native-month-year-picker#27]
App is crashing when opening picker 
Using:
"react-native": "0.62.2"
"react-native-month-year-picker": "^1.3.2",

Code:
import React, { useState, useCallback } from 'react';
import { View, SafeAreaView, Text,TouchableOpacity } from 'react-native';
import MonthPicker from 'react-native-month-year-picker';
 
const App = () => {
  const [date, setDate] = useState(new Date());
  const [show, setShow] = useState(false);
 
  const showPicker = useCallback((value) => setShow(value), []);
 
  const onValueChange = useCallback(
    (event, newDate) => {
      const selectedDate = newDate || date;
 
      showPicker(false);
      setDate(selectedDate);
    },
    [date, showPicker],
  );
 
  return (
    <SafeAreaView>
      <Text>Month Year Picker Example</Text>
      {/* <Text>{moment(date, "MM-YYYY")}</Text> */}
      <TouchableOpacity onPress={() => showPicker(true)}>
        <Text>OPEN</Text>
      </TouchableOpacity>
      {show && (
        <MonthPicker
          onChange={onValueChange}
          value={date}
          minimumDate={new Date()}
          maximumDate={new Date(2025, 5)}
          enableAutoDarkMode={false}
        />
      )}
    </SafeAreaView>
  );
};
 
export default App;

Tried following steps but not working
react-native run-android 
npm start --reset-cache

**Comment by gusparis** [comment]
@choudhary1200 The code you shared is working. Do you happen to have the error log?

**Comment by choudhary1200** [comment]
> @choudhary1200 The code you shared is working. Do you happen to have the error log?
> 
> edit: why is the `Month Year Picker Example` not either commented nor wrapped by a `<Text>`?
I am getting below native error
Didn't find class "java.time.instant"
See below attached screenshot for more details.

Device Info:
Android 7
minSdkVersion 19 

![Screenshot_2020-08-08-14-27-54](https://user-images.githubusercontent.com/11774050/89706497-e2f6f500-d983-11ea-9b42-0f8e956efc11.png)

**Comment by gusparis** [comment]
@choudhary1200 your Android version is lower 8.0. That's why the class is missing.

**Comment by gusparis** [comment]
Let me see if I can introduce a lower version workaround
