### ISSUE TITLE
Incorrect work on android

### ISSUE THREAD

**Issue by vivaLaChoco** [gusparis/react-native-month-year-picker#3]
when I clicked Ok at dialog, then picker opens multiple times and doesn't close, i can do it only by clicking on Ok button
and I can't see action for Cancel button, and can't setVisible for modal like "false" value and modal always visible. 
please help

**Comment by gusparis** [comment]
I’ll check it

**Comment by gusparis** [comment]
@vivaLaChoco can you share the piece of code where you are using the component? I'm not able to reproduce that behavior in the example. Also, for the cancel button action, I didn't want to add a lot of different props for iOS and Android, so the actions can be caught through the `event`. eg. in Android you have these two events:
```
ACTION_DATE_SET = 'dateSetAction'
ACTION_DISMISSED = 'dismissedAction'
```
Please let me know if that works for you.

**Comment by Zonfer** [comment]
UP ip. This problem was fixed? I have the same issue

**Comment by gusparis** [comment]
Just did an update to the readme's usage section with a working example. Can you guys try it?

**Comment by vivaLaChoco** [comment]
after click on "Ok" button  it works fine, thank you
as I understand, onChange doesn't call, when event is "dismissedAction", that's why flag "show" is true, and when you clicked on button "Open picker", picker wouldn't open
and I can't understand, why. Can you help me please?

**Comment by gusparis** [comment]
The onChange method returns an event and the selected date. If the dialog was canceled, the event will be “dismissedAction”. You can perform the a check (a switch if you like) to trigger needed actions. eg
```
const onDateChange = (event, newDate) => {
     switch (event) {
          case ACTION_DATE_SET:
               setDate(newDate);
          case ACTION_DISMISSED:
          default:
                doSomeErrorHandlingHere();
     }
} 
```
Notice that when event is other than `ACTION_DATE_SET`, newDate will be `undefined`.

**Comment by Zonfer** [comment]
I'm testing and the example at the README's section work's fine with function setShow. But still have a litle bug with close and open modal events. ACTION_DATE_SET, and ACTION_DISMISSED, doesn't exist theses events.
