### ISSUE TITLE
this.props.onChange is not a function 

### ISSUE THREAD

**Issue by nolife08021** [gusparis/react-native-month-year-picker#33]
Error when i press the ok button.

![Screen Shot 2020-09-07 at 10 32 01 AM](https://user-images.githubusercontent.com/49778835/92343108-6af02c00-f0f5-11ea-8b35-04d3e1e114b9.png)

**Comment by gusparis** [comment]
@nolife08021 Thanks for using the library! You are not sending the `onChange` function to the component. Nevertheless, I marked that prop as optional in the README, so I should have to be perfoming a check before firing it.

**Comment by gusparis** [comment]
@nolife08021 try new version (1.3.5). I made a null checking of onChange prop on #33
