### ISSUE TITLE
localization 

### ISSUE THREAD

**Issue by waohwaohwaoh** [gusparis/react-native-month-year-picker#34]
Hello, can you please tell me how to make localization for this picker, or is this function not yet implemented? If not, is it planned to be implemented in the near future?

**Comment by gusparis** [comment]
Hello @waohwaohwaoh and thank you for using the library! Currently, the month names are being fetch on native sides, both by Java and Objective-C getting localized names based on phone settings. Is that what you need? Regards.

**Comment by waohwaohwaoh** [comment]
Thanks for the quick answer, yes this is what I want, but on my emulator, the Russian language is specified in the settings, the names of the months are still in English. Does this work on an emulator or only on real devices?

**Comment by gusparis** [comment]
mmm I really don't remember if it worked on the sim. Let me check on my personal device that's in Spanish

**Comment by waohwaohwaoh** [comment]
Thanks for your work on the library and for your quick response. Could you please tell us the approximate terms of elimination of this defect

**Comment by gusparis** [comment]
@waohwaohwaoh it was an easy fix. CI is already running...waiting for new version to be published

**Comment by waohwaohwaoh** [comment]
a lot thx you, I will follow the update
