### ISSUE TITLE
Months do not follow the device's default language

### ISSUE THREAD

**Issue by manoelramos** [gusparis/react-native-month-year-picker#36]
It would be interesting if the months were translated into the native language of the device. I believe the iOS DatePicker, do this by default.

**Comment by gusparis** [comment]
hey @manoelramos! Thanks for using the library! I don't know what version you're using, but this is currently supported.

**Comment by manoelramos** [comment]
I'm using the version 1.3.4. I closed the issue when I saw the issue #34 

thanks for reply and nice job, man.
