### ISSUE TITLE
on IOS, it's always dark mode

### ISSUE THREAD

**Issue by giftset** [gusparis/react-native-month-year-picker#37]
on IOS,
even though i set enableAutoDarkMode as false, the color of picker is still dark mode style.

how can i fix this?

**Comment by jennifersalas** [comment]
+1 I see this issue as well.

**Comment by gusparis** [comment]
@giftset @jennifersalas Hello! Thanks for using the library! I'm aware of that issue. Currently working on a new release with a few improvements and fixes.

**Comment by gusparis** [comment]
Fixed on #38
