### ISSUE TITLE
Receiving invalid date for all input on android

### ISSUE THREAD

**Issue by jennifersalas** [gusparis/react-native-month-year-picker#39]
As of 1.4.0, android side is returning 'Invalid Date' to the onChange callback for any value selected.

**Comment by jennifersalas** [comment]
Fixed invalid date by changing MonthPicker.android.js line 29 to:

```
          date = moment(new Date(year, month), NATIVE_FORMAT).format(
```

On a related note, the returned month does not match the selected month.
The maximum month/year is also off by one month.

**Comment by gusparis** [comment]
Thanks for using the library! I will push a new version with the fix in an hour or two.
