### ISSUE TITLE
Has any event to listen when modal is going to close?

### ISSUE THREAD

**Issue by Zonfer** [gusparis/react-native-month-year-picker#4]
Is there an event that is fired when modal was closed? 
Clicking on the button Ok, or Cancel from the onChange function it's ok and changes the value. But when you click outside of the modal, and the modal was closed without clicking on button Cancel our Ok,  i am no longer able to open the modal and select a new date. Help

**Comment by Zonfer** [comment]
In Modal from React Native has a event named onRequestClose. Maybe if you find out it works

**Comment by gusparis** [comment]
Hey! I was actually working on a callback for Android when clicking the overlay, plus a different approach for the iOS picker.

**Comment by Zonfer** [comment]
And how long do you think it will take to develop this improvement?

**Comment by gusparis** [comment]
@Zonfer just made a couple of updates to both, Android and iOS. Can you check them?

**Comment by Zonfer** [comment]
Where? The last release have 20 days old

**Comment by gusparis** [comment]
npm. forgot to update GH tag versions, and the semantic+circle got fucked up somehow. will check it tomorrow after work.
