### ISSUE TITLE
On first load, the value does not match default

### ISSUE THREAD

**Issue by jennifersalas** [gusparis/react-native-month-year-picker#40]
On the first time loading the picker, the value is set incorrectly. This behavior is not present in the android version. Below the Value should have been September 2020.

<img width="377" alt="Screen Shot 2020-09-25 at 4 22 34 PM" src="https://user-images.githubusercontent.com/12005979/94323624-64621100-ff4b-11ea-8b2c-23655999dbb0.png">

**Comment by gusparis** [comment]
Hey @jennifersalas! Thank you for all your findings! I made some changes on latest version that broke this. Will upload a fix along with your other posted issue. 😊
