### ISSUE TITLE
"RNMonthPicker" was not found in the UIManager using Expo

### ISSUE THREAD

**Issue by lvegh** [gusparis/react-native-month-year-picker#42]
Hey,

First of all thanks for creating this datepicker.

I am using the following packages:
Expo: "expo": "^39.0.3"
"react-native": "^0.63.2"

I have installed the package using:
npm install react-native-month-year-picker --save

As per my knowledge there is no linking/autolinking in a managed expo project so the quesiton is how can i make it work?

When i tap on the button to show the datepicker i get the following error:
"RNMonthPicker" was not found in the UIManager

Many thanks,
Trix

**Comment by gusparis** [comment]
Hey @lvegh! Thank you for using the library. Unfortunately, Expo does not support libraries with nagive code. With Expo, you write just JavaScript and a set of native APIs that the Expo team maintains and upgrades. I leave you here a link to Expo documentation on third-party libraries for future reference: https://docs.expo.io/workflow/using-libraries/#determining-third-party-library-compatibility
