### ISSUE TITLE
Couldn't install it using yarn 

### ISSUE THREAD

**Issue by mohamadmek** [gusparis/react-native-month-year-picker#45]
mohamadmek@Mohamads-MacBook-Pro centreminefrontend % yarn add @react-native-month-year-picker       
yarn add v1.22.5
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-month-year-picker: Request \"https://registry.yarnpkg.com/@react-native-month-year-picker\" returned a 405".
info If you think this is a bug, please open a bug report with the information provided in "/Users/mohamadmek/Documents/CentremineProject/centreminefrontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
mohamadmek@Mohamads-MacBook-Pro centreminefrontend %

**Comment by gusparis** [comment]
Hello! Thanks for using the library. I don't think this is the right way of opening an issue or bug, but anyway I made a typo on the readme for the yarn installation, it shouldn't have the @. Try `yarn add react-native-month-year-picker`. Let me know how it works

**Comment by mohamadmek** [comment]
Hello, sorry this the first time I submit an issue it worked thank you so
much for your fast reply

**Comment by gusparis** [comment]
No worries! Stay safe ✌🏻
