### ISSUE TITLE
okButton & cancelButton not working (iOS)

### ISSUE THREAD

**Issue by tommaso-sebastianelli** [gusparis/react-native-month-year-picker#52]
okButton & cancelButton props work on Android but don't work in iOS (default values are shown):

Simulator: iPhone 11 (iOS 13.2.2), iPhone 11 (iOS 14)
react native: 0.63.2
react-native-month-year-picker: 1.6.0

**Comment by gusparis** [comment]
Hey @tommaso-sebastianelli Thank you for using the library. Nice catch, I missed it. I'll deploy a fix asap.
