### ISSUE TITLE
TypeError: null is not an object (evaluating '_RNMonthPickerDialogModule.default.open')

### ISSUE THREAD

**Issue by auliakbarh** [gusparis/react-native-month-year-picker#54]
I've an error when using MonthPicker from 'react-native-month-year-picker' (Android devices)
I guess it's happens because the auto linking doesn't run automatically. Is there any guide to install dependencies manually on Android and iOS?
<img width="298" alt="Screen Shot 2020-11-30 at 11 58 48" src="https://user-images.githubusercontent.com/5032631/100570487-75d8e800-3303-11eb-99b8-db193e9cc8f4.png">

**Comment by gusparis** [comment]
Hello @auliakbarh! What's your RN version?

**Comment by auliakbarh** [comment]
> Hello @auliakbarh! What's your RN version?

I'm using RN 0.62.2, and using existing the native app (ios & android)

**Comment by gusparis** [comment]
Weird. That version already has autolinking. Did you build the app? Did you try running a gradle sync from Android Studio? Is this happening to you also on iOS?

**Comment by gusparis** [comment]
I'll close this due to inactivity.

**Comment by augustoost** [comment]
I've the same issue. 

- RN version 0.63.4
- Expo with Bare workflow.

I've already try to link manually, but don't work as well.

**Comment by augustoost** [comment]
I can't reproduce the error on iOS, so I don't know if this error happens only in the Android.

**Comment by gusparis** [comment]
Ok, I'll reopen it. Can you share me your `android/settings.gradle` and your `android/app/build.gradle` files?

**Comment by mixermat99** [comment]
i have the same issue using Expo client, RN version: 0.63.2

**Comment by gusparis** [comment]
@mixermat99 the component is not compatible with Expo, at least not with the Managed workflow. Are you using Bare?

**Comment by mixermat99** [comment]
No, i'm using Managed Workflow

**Comment by gusparis** [comment]
@mixermat99 check my edited comment. I'm sorry, but Expo won't support it.

**Comment by mixermat99** [comment]
Ok, thanks very much

**Comment by gusparis** [comment]
@mixermat99 sorry you can't use it! 😔

**Comment by mixermat99** [comment]
nothing, your library for me is the best moth/year picker online, is for this reason that i would use that

**Comment by vksgautam1** [comment]
we have version of 0.59.4 and have this issue , is there any solution for it

**Comment by Rishabhcore7** [comment]
i'm getting the same crash in 0.59.4, can someone help me please.

**Comment by gusparis** [comment]
Hey! I was off. I recommend using RN 0.60+, there are some issues with lower versions. Either way, I'll set up a 0.59 env to check Android.

**Comment by minhtbvnist** [comment]
i'm getting the same crash in 0.63.3, can someone help me please. (Android)
![192656333_543687363703545_2115853174232145014_n](https://user-images.githubusercontent.com/67574123/120154000-95e95580-c219-11eb-91a0-01de635a141d.jpg)

**Comment by imnotvirus** [comment]
I have the same problem using EXPO

**Comment by ryandever** [comment]
Please does anyone solved this problem? I'm using RN 0.68.2 and got the same problem
