### ISSUE TITLE
RNMontPicker was not found in UIManager

### ISSUE THREAD

**Issue by nwpnkmngm** [gusparis/react-native-month-year-picker#59]
my code

  <MonthYearPicker
                locale="ko"
                onChange={date => console.log(date)}
                minimumDate={new Date()}
                maximumDate={new Date(2025, 5)}
                value={new Date()} />

**Comment by gusparis** [comment]
hey! what RN version are you using? did you link the library? Are you running on Expo?

**Comment by gusparis** [comment]
I'll close this due to inactivity.

**Comment by search654321** [comment]
Hi get the same issue, I'm on expo
