### ISSUE TITLE
Error in release mode iOS

### ISSUE THREAD

**Issue by nwpnkmngm** [gusparis/react-native-month-year-picker#62]
I got error on release iOS application 

when I select month and year on release I can get any year that I selected  but  I still got January month when submit.
It's work on simulator and debug mode on device.

**Comment by gusparis** [comment]
hey @nwpnkmngm! thanks for using the library! Weird thing you're experiencing...I will look into it.

**Comment by nwpnkmngm** [comment]
@gusparis  I'm not sure you have the same problem with me, I need you to try release iOS app out and test with this picker because I have problem with any picker like this one such as DatePicker etc.

**Comment by gusparis** [comment]
Yeah, couldn't reproduce your issue. RN and iOS versions?

**Comment by gusparis** [comment]
Closed due to inactivity.
