### ISSUE TITLE
can you adding autotheme false/true to android?

### ISSUE THREAD

**Issue by agungs17** [gusparis/react-native-month-year-picker#63]

**Comment by gusparis** [comment]
Hey! @agungs17 what do you mean? Having the light theme no matter phone's mode?

**Comment by agungs17** [comment]
I need theme mode to turn off and on light and dark mode or other options such as changing background color, text color, etc.

**Comment by gusparis** [comment]
I'll label it as enhancement. Let me see what I can do.

**Comment by agungs17** [comment]
thankyou bro @gusparis

**Comment by agungs17** [comment]
any update?

**Comment by gusparis** [comment]
Hey! how's it going? it's been crazy these couple of weeks. Have a lot of issues reported on the lib that I couldn't take care of. I will work on them this week for sure.
