### ISSUE TITLE
Not supporting to all versions in android

### ISSUE THREAD

**Issue by nani0531** [gusparis/react-native-month-year-picker#64]
@gusparis this module is not working in some versions in the android 5 & 11, in android version 9 it is working,

i didn't checked in remaining versions also, only i tested in above mentioned versions. it was working only in android 9

not working in android 11 & 5

can you help me to fix this issue.
Thanks

**Comment by gusparis** [comment]
@nani0531 weird...I didn't use any high API specific method/annotation. It should work on API 16 (Android 4.1) and newer. And about API 30, I never tested on it yet. Let me take a look.
