### ISSUE TITLE
scrolling month and year at a time picker getting freez

### ISSUE THREAD

**Issue by nani0531** [gusparis/react-native-month-year-picker#65]
@gusparis  i tested the picker in different ways, it was getting freeze, 
when i start scrolling the date and year same time, after some time application getting closed

can you help me in it to fix this issue.

Thanks

**Comment by gusparis** [comment]
@nani0531 Hello! Platform?

**Comment by nani0531** [comment]
@gusparis android

**Comment by gusparis** [comment]
Because of the way it is implemented, it is possible for that to happen. Who scrolls both pickers at the same time anyway? 🤔

**Comment by gusparis** [comment]
Let me review it.
