### ISSUE TITLE
It's still possible to select a date beyond min/max

### ISSUE THREAD

**Issue by apgsn** [gusparis/react-native-month-year-picker#66]
The way you do it is by clicking the ok button before the scrolling animation outside min/max boundaries has ended.  
Android only, v. 1.6.3.

**Comment by gusparis** [comment]
Hey @apgsn! yeah...scrolling animation is causing a lot of issues on Android. I will have to remove it or disable the whole component while animating 🤷🏻‍♂️. I'll review it today afternoon.

**Comment by apgsn** [comment]
Eventually I found a quick fix by testing the returned date against min/max values before invoking the callback associated to `ACTION_DATE_SET`, maybe you can do something like that but within the component.

**Comment by gusparis** [comment]
hacky 😎
