### ISSUE TITLE
[Request] Please provide index.d.ts for typescript

### ISSUE THREAD

**Issue by csohei** [gusparis/react-native-month-year-picker#67]
Dear contributors.

I found this repo yesterday and am thinking this is exactly what I want.

However, since I am using the Typescript and cannot use the component without suppressing type error.
To use your component, I would like you to provide the typedef as a part of the code provided.

If you do not mind me contributing, I can make PR by myself in this weekend or next week.

Best Regard

**Reference:** 
[Typescript Official Document: Modules .d.ts](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html)

**Comment by gusparis** [comment]
Hey @csohei! How's it going? Yes, adding ts support was on my routemap, but couldn't find the time yet to work on it. If you want to contribute go ahead! I'd gladly review your PR and help you with anything you need.

**Comment by SaadBinWaheed-empglabs** [comment]
Any update on TS support?

**Comment by androidfanatic** [comment]
+1

**Comment by jeandejavu** [comment]
+1

**Comment by eminsr** [comment]
Please check out the PR #99 and feel free to improve if necessary.
