### ISSUE TITLE
Is there a way not to present the wheel inside the modal?

### ISSUE THREAD

**Issue by tamir61** [gusparis/react-native-month-year-picker#68]
Hi, 
basically, I need only the wheel picker itself without the modal functionality. 

is there a way to do it? 

Thanks

**Comment by gusparis** [comment]
@tamir61 This has also been requested in the past. I will have to work mostly on the Android implementation of it, but I think it can be achieved. I'll keep you posted.

**Comment by pedrogarciyalopez** [comment]
@gusparis is there any progress?

**Comment by widianapw** [comment]
Hi @gusparis , is there any updates?
