### ISSUE TITLE
Help me out to get the cancel button call back

### ISSUE THREAD

**Issue by harishmurali94** [gusparis/react-native-month-year-picker#7]

**Comment by gusparis** [comment]
Can you share me the piece of code you are using for the `onChange` callback?

**Comment by harishmurali94** [comment]
@gusparis  <MonthPicker
                  onChange={this._handleDatePicked}
                  value={new Date()}
                  minimumDate={new Date(2018, 5)}
                  maximumDate={new Date(2035, 5)}
                />
this is my onchange function
 _handleDatePicked = (event, newDate) => {
    console.log('EVENT', event);
}
on this when i click cancel i am not getting any response on event

**Comment by harishmurali94** [comment]
@gusparis for me on android when i close the pop up using cancel and go to next page and come back to same page automatically the modal is getting opened without calling the picker. Facing the same when clicking outside the modal also

**Comment by gusparis** [comment]
Will check about the event. Receiving it correctly on example. About the closing, are you setting the show/not show prop?

**Comment by harishmurali94** [comment]
Yes i am handling the show prop on my side

**Comment by harishmurali94** [comment]
how to get close button call back

**Comment by harishmurali94** [comment]
@gusparis Hi thanks for the time when i updated the library it is working fine
