### ISSUE TITLE
Not showing Done and Cancel Button on IOS

### ISSUE THREAD

**Issue by Rishabhcore7** [gusparis/react-native-month-year-picker#70]
React Native version :0.59:4

**Comment by Rishabhcore7** [comment]
Thanks Resolved , Linked Manually.

**Comment by gusparis** [comment]
@Rishabhcore7 hello! thanks for using the library. A very weird issue...can you send a screenshot of it? also, are you sending some label props to the component, or trying to use the default ones?

**Comment by gusparis** [comment]
@Rishabhcore7 Not working as expected with RN < 0.60, as stated on project peer dependencies.

**Comment by bigbean17** [comment]
I got the same issue, my RN is 0.64
![image](https://user-images.githubusercontent.com/69971426/156490299-9c2a8b2d-7ea2-4a5a-ad74-cd915755b7ec.png)
