### ISSUE TITLE
Issue after installing mac os big sur - Execution failed for task ':react-native-month-year-picker:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by chamila-ascentic** [gusparis/react-native-month-year-picker#88]
> Task :react-native-month-year-picker:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
348 actionable tasks: 2 executed, 1 from cache, 345 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-month-year-picker:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDevDebug -PreactNativeDevServerPort=8081

**Comment by gusparis** [comment]
@chamila-ascentic try cleaning up cache. Tested myself the project on a M1 chip running OS Ventura.
